Team_1_Finance_(Major_Project)/IKart/IKart_Client/Controllers/Admin/ProductsController.cs
using System;

using System.Collections.Generic;

using System.Linq;

using System.Web.Mvc;

using System.Net.Http;

using IKart_Shared.DTOs.Admin;

using Newtonsoft.Json;

using System.Text;

using System.IO;

using System.Web;

namespace IKart_Client.Controllers

{

    public class ProductsController : Controller

    {

        string apiUrl = "https://localhost:44365/api/products";

        string stocksApiUrl = "https://localhost:44365/api/stocks";


        public ActionResult Index()

        {

            List<ProductDto>

    products = new List<ProductDto>

        ();

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.GetAsync(apiUrl).Result;

                    if (res.IsSuccessStatusCode)

                    {

                        var data = res.Content.ReadAsStringAsync().Result;

                        products = JsonConvert.DeserializeObject<List<ProductDto>>(data);

                    }

                }

            }

            return View(products);

        }


        public ActionResult Create()

        {

            PopulateStocksDropdowns();

            return View();

        }

        [HttpPost]

        [ValidateAntiForgeryToken]

        public ActionResult Create(ProductDto product, HttpPostedFileBase ProductImageFile)

        {

            if (ModelState.IsValid)

            {

                if (ProductImageFile != null && ProductImageFile.ContentLength > 0)

                {

                    string fileName = Path.GetFileName(ProductImageFile.FileName);
                    string folderPath = Server.MapPath("~/Content/ProductImages/");

                    if (!Directory.Exists(folderPath))

                    {

                        Directory.CreateDirectory(folderPath);

                    }

                    string filePath = Path.Combine(folderPath, fileName);

                    ProductImageFile.SaveAs(filePath);


                    product.ProductImage = fileName;

                }

                // ✅ Allow self-signed SSL certs (development only!)

                System.Net.ServicePointManager.ServerCertificateValidationCallback =

                    (sender, cert, chain, sslPolicyErrors) => true;

                // ✅ Call API

                using (var client = new HttpClient())

                {

                    client.BaseAddress = new Uri(apiUrl);

                    var json = JsonConvert.SerializeObject(product);

                    var content = new StringContent(json, Encoding.UTF8, "application/json");

                    var response = client.PostAsync("", content).Result;

                    if (response.IsSuccessStatusCode)

                    {

                        return RedirectToAction("Index");

                    }

                    else

                    {

                        ModelState.AddModelError("", "Error: " + response.ReasonPhrase);

                    }

                }

            }

            return View(product);

        }


        public ActionResult Edit(int id)

        {

            ProductDto dto = null;

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.GetAsync($"{apiUrl}/{id}").Result;

                    if (res.IsSuccessStatusCode)

                    {

                        var data = res.Content.ReadAsStringAsync().Result;

                        dto = JsonConvert.DeserializeObject<ProductDto>(data);

                    }

                }

            }

            if (dto == null)

                return HttpNotFound();

            PopulateStocksDropdowns(dto);

            return View(dto);

        }


        [HttpPost]

        public ActionResult Edit(int id, ProductDto dto)

        {

            if (!ModelState.IsValid)

            {

                PopulateStocksDropdowns(dto);

                return View(dto);

            }

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var json = JsonConvert.SerializeObject(dto);

                    var data = new StringContent(json, Encoding.UTF8, "application/json");

                    var res = client.PutAsync($"{apiUrl}/{id}", data).Result;

                    if (res.IsSuccessStatusCode)

                        return RedirectToAction("Index");

                }

            }

            PopulateStocksDropdowns(dto);

            return View(dto);

        }

        public ActionResult Delete(int id)

        {

            ProductDto dto = null;

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.GetAsync($"{apiUrl}/{id}").Result;

                    if (res.IsSuccessStatusCode)

                    {

                        var data = res.Content.ReadAsStringAsync().Result;

                        dto = JsonConvert.DeserializeObject<ProductDto>(data);

                    }

                }

            }

            if (dto == null)

                return HttpNotFound();

            return View(dto);

        }


        [HttpPost, ActionName("Delete")]

        public ActionResult DeleteConfirmed(int id)

        {

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.DeleteAsync($"{apiUrl}/{id}").Result;

                    if (res.IsSuccessStatusCode)

                        return RedirectToAction("Index");

                }

            }

            return RedirectToAction("Index");

        }


        public ActionResult Reports()

        {

            List<StocksDto> stocks;

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.GetAsync("https://localhost:44365/api/stocks").Result;

                    if (res.IsSuccessStatusCode)

                    {

                        var data = res.Content.ReadAsStringAsync().Result;

                        stocks = JsonConvert.DeserializeObject<List<StocksDto>>(data);

                    }

                    else

                    {

                        stocks = new List<StocksDto>();

                    }

                }

            }

            var report = stocks

                .GroupBy(s => new { s.Category, s.SubCategory })

                .Select(g => new StocksDto

                {

                    Category = g.Key.Category,

                    SubCategory = g.Key.SubCategory,

                    TotalStocks = g.Sum(x => x.TotalStocks) ?? 0,

                    AvailableStocks = g.Sum(x => x.AvailableStocks) ?? 0

                })

                .OrderBy(r => r.Category)

                .ThenBy(r => r.SubCategory)

                .ToList();

            return View(report);

        }


        #region Helper Methods

        private void PopulateStocksDropdowns(ProductDto dto = null)

        {

            List<StocksDto> stocks = new List<StocksDto>();

            using (var handler = new HttpClientHandler())

            {

                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;

                using (HttpClient client = new HttpClient(handler))

                {

                    var res = client.GetAsync(stocksApiUrl).Result;

                    if (res.IsSuccessStatusCode)

                    {

                        var data = res.Content.ReadAsStringAsync().Result;

                        stocks = JsonConvert.DeserializeObject<List<StocksDto>>(data);

                    }

                }

            }

            ViewBag.Categories = new SelectList(stocks.Select(s => s.Category).Distinct(), dto?.CategoryName);

            ViewBag.Stocks = stocks;

        }

        #endregion

    }

}

Team_1_Finance_(Major_Project)/IKart/IKart_Client/Controllers/Admin/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web.Mvc;
using IKart_ClientSide.Filters;
using IKart_Shared.DTOs.Admin;
using Newtonsoft.Json;

namespace IKart_Client.Controllers
{
    [AdminAuthorize]
    public class StocksController : Controller
    {
        string apiUrl = "https://localhost:44365/api/stocks";

        // LIST ALL
        public ActionResult Index()
        {
            List<StocksDto> stocks = new List<StocksDto>();
            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.GetAsync(apiUrl).Result;
                    if (res.IsSuccessStatusCode)
                    {
                        var json = res.Content.ReadAsStringAsync().Result;
                        stocks = JsonConvert.DeserializeObject<List<StocksDto>>(json);
                    }
                }
            }
            return View(stocks);
        }

        public ActionResult Create()
        {
            ViewBag.Categories = GetExistingCategories();
            return View(new StocksDto()); 
        }

        // CREATE POST
        [HttpPost]
        public ActionResult Create(StocksDto dto)
        {
            ViewBag.Categories = GetExistingCategories();

            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.GetAsync(apiUrl).Result;
                    if (res.IsSuccessStatusCode)
                    {
                        var json = res.Content.ReadAsStringAsync().Result;
                        var stocks = JsonConvert.DeserializeObject<List<StocksDto>>(json);
                        bool exists = stocks.Any(s =>
                            string.Equals(s.Category?.Trim(), dto.Category?.Trim(), StringComparison.OrdinalIgnoreCase)
                            && string.Equals(s.SubCategory?.Trim(), dto.SubCategory?.Trim(), StringComparison.OrdinalIgnoreCase)
                        );
                        if (exists)
                        {
                            ModelState.AddModelError("Category", "This Category and SubCategory combination already exists.");
                            return View(dto); 
                        }
                    }
                }
            }

            if (!ModelState.IsValid) return View(dto); 

            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    dto.AvailableStocks = null;
                    var json = JsonConvert.SerializeObject(dto);
                    var data = new StringContent(json, Encoding.UTF8, "application/json");
                    var res = client.PostAsync(apiUrl, data).Result;
                    if (res.IsSuccessStatusCode) return RedirectToAction("Index");
                }
            }
            return View(dto);
        }

        public ActionResult Edit(int id)
        {
            StocksDto stock = null;
            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.GetAsync(apiUrl + "/" + id).Result;
                    if (res.IsSuccessStatusCode)
                    {
                        var json = res.Content.ReadAsStringAsync().Result;
                        stock = JsonConvert.DeserializeObject<StocksDto>(json);
                    }
                }
            }
            return View(stock);
        }


        [HttpPost]
        public ActionResult Edit(int id, StocksDto dto)
        {
            if (!ModelState.IsValid) return View(dto);

            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var json = JsonConvert.SerializeObject(dto);
                    var data = new StringContent(json, Encoding.UTF8, "application/json");
                    var res = client.PutAsync(apiUrl + "/" + id, data).Result;
                    if (res.IsSuccessStatusCode) return RedirectToAction("Index");
                }
            }
            return View(dto);
        }


        public ActionResult Delete(int id)
        {
            StocksDto stock = null;
            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.GetAsync(apiUrl + "/" + id).Result;
                    if (res.IsSuccessStatusCode)
                    {
                        var json = res.Content.ReadAsStringAsync().Result;
                        stock = JsonConvert.DeserializeObject<StocksDto>(json);
                    }
                }
            }

            if (stock == null) return HttpNotFound();
            return View(stock);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.DeleteAsync(apiUrl + "/" + id).Result;

                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else if (res.StatusCode == HttpStatusCode.Conflict)
                    {
                        var errorMsg = res.Content.ReadAsStringAsync().Result;
                        ViewBag.Error = errorMsg;

                        var stockRes = client.GetAsync(apiUrl + "/" + id).Result;
                        if (stockRes.IsSuccessStatusCode)
                        {
                            var json = stockRes.Content.ReadAsStringAsync().Result;
                            var stock = JsonConvert.DeserializeObject<StocksDto>(json);
                            return View("Delete", stock);
                        }
                        return View("Delete");
                    }
                }
            }

            return RedirectToAction("Index");
        }

        private List<string> GetExistingCategories()
        {
            List<StocksDto> stocks = new List<StocksDto>();
            using (var handler = new HttpClientHandler())
            {
                handler.ServerCertificateCustomValidationCallback = (sender, cert, chain, errors) => true;
                using (var client = new HttpClient(handler))
                {
                    var res = client.GetAsync(apiUrl).Result;
                    if (res.IsSuccessStatusCode)
                    {
                        var json = res.Content.ReadAsStringAsync().Result;
                        stocks = JsonConvert.DeserializeObject<List<StocksDto>>(json);
                    }
                }
            }
            return stocks.Select(s => s.Category)
                         .Where(c => !string.IsNullOrWhiteSpace(c))
                         .Distinct()
                         .OrderBy(x => x)
                         .ToList();
        }
    }
}

Team_1_Finance_(Major_Project)/IKart/IKart_Client/Views/Products/Create.cshtml
@model IKart_Shared.DTOs.Admin.ProductDto

@using Newtonsoft.Json

@{
                Layout = "~/Views/Shared/_AdminLayout.cshtml";

                ViewBag.Title = "Add Product";

}

<div class="container mt-4">
    <div class="card shadow-sm border-0">
        <div class="card-body">
            <h2 class="text-center mb-4">@ViewBag.Title</h2>

            @using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))

            {

                @Html.AntiForgeryToken()

                                <div class="mb-3">

                                    @Html.LabelFor(m => m.ProductName, new { @class = "form-label fw-bold" })

                                    @Html.TextBoxFor(m => m.ProductName, new { @class = "form-control" })
                                </div>

                                                <div class="mb-3">

                                                    @Html.LabelFor(m => m.ProductDetails, new { @class = "form-label fw-bold" })

                                                    @Html.TextAreaFor(m => m.ProductDetails, new { @class = "form-control", rows = 3 })
                                                </div>

                                                                <div class="mb-3">

                                                                    @Html.LabelFor(m => m.Cost, new { @class = "form-label fw-bold" })

                                                                    @Html.TextBoxFor(m => m.Cost, new { @class = "form-control", type = "number", step = "0.01" })
                                                                </div>

                                                                                <div class="row g-3 mb-3">
                                                                                    <div class="col-md-4">

                                                                                        @Html.Label("Category", new { @class = "form-label fw-bold" })

                                                                                        @Html.DropDownList("Category", (SelectList)ViewBag.Categories, "Select Category", new { @class = "form-select", id = "categoryDropdown" })
                                                                                    </div>

                                                                                    <div class="col-md-4">

                                                                                        @Html.Label("SubCategory", new { @class = "form-label fw-bold" })
                                                                                        <select id="subCategoryDropdown" class="form-select"></select>
                                                                                    </div>

                                                                                    <div class="col-md-4">

                                                                                        @Html.Label("Stock", new { @class = "form-label fw-bold" })
                                                                                        <select id="stockDropdown" name="Stock_Id" class="form-select"></select>
                                                                                    </div>
                                                                                </div>

                                                                                                <div class="mb-3">

                                                                                                    @Html.Label("Product Image", new { @class = "form-label fw-bold" })
                                                                                                    <input type="file" name="ProductImageFile" class="form-control" accept="image/*" />
                                                                                                </div>

                                                                                                                <div class="d-flex justify-content-center gap-3 mt-4">
                                                                                                                    <button type="submit" class="btn btn-success px-4">Save</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                                                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                                                                    <a href="@Url.Action("Index")" class="btn btn-outline-secondary px-4">Cancel</a>
                                                                                                                </div>
                                                                                                                            }
        </div>
    </div>
</div>

@section Scripts {
    <script>

        var allStocks = @Html.Raw(JsonConvert.SerializeObject(ViewBag.Stocks));

        $('#categoryDropdown').change(function () {

            var cat = $(this).val();

            var subCats = allStocks.filter(s => s.Category === cat).map(s => s.SubCategory);

            subCats = [...new Set(subCats)];

            var subDropdown = $('#subCategoryDropdown');

            subDropdown.empty().append('<option>Select SubCategory</option>');

            subCats.forEach(sc => subDropdown.append('<option>' + sc + '</option>'));

            $('#stockDropdown').empty().append('<option>Select Stock</option>');

        });

        $('#subCategoryDropdown').change(function () {

            var cat = $('#categoryDropdown').val();

            var sub = $(this).val();

            var stocks = allStocks.filter(s => s.Category === cat && s.SubCategory === sub);

            var stockDropdown = $('#stockDropdown');

            stockDropdown.empty().append('<option>Select Stock</option>');

            stocks.forEach(s => stockDropdown.append('<option value="' + s.StockId + '">Stock ' + s.StockId + ' - Available: ' + s.AvailableStocks + '</option>'));

        });
    </script>

}

Team_1_Finance_(Major_Project)/IKart/IKart_Client/Views/Products/Delete.cshtml
@model IKart_Shared.DTOs.Admin.ProductDto

@using Newtonsoft.Json

@{
                Layout = "~/Views/Shared/_AdminLayout.cshtml";

                ViewBag.Title = "Delete Product";

}

<div class="container mt-4">
    <div class="card shadow-sm border-0">
        <div class="card-body text-center" style="min-height: 250px;">
            <h2 class="mb-4">@ViewBag.Title</h2>

            <div class="alert alert-warning fw-bold">

                Are you sure you want to delete the product:
                <strong>@Model.ProductName</strong>?
            </div>

            @using (Html.BeginForm("Delete", "Products", FormMethod.Post))

            {

                @Html.AntiForgeryToken()

                                @Html.HiddenFor(m => m.ProductId)

                                                <div class="d-flex justify-content-center gap-3 mt-4">
                                                    <button type="submit" class="btn btn-danger px-4">Yes, Delete</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <a href="@Url.Action("Index")" class="btn btn-outline-secondary px-4">Cancel</a>
                                                </div>
                                                            }
        </div>
    </div>
</div>

Team_1_Finance_(Major_Project)/IKart/IKart_Client/Views/Products/Index.cshtml
@model List<IKart_Shared.DTOs.Admin.ProductDto>

@using Newtonsoft.Json

@{
                Layout = "~/Views/Shared/_AdminLayout.cshtml";

                ViewBag.Title = "Manage Products";

}
<div class="card shadow-sm border-0 flex-grow-1" style="min-height: 400px;">
    <div class="container mt-4 text-center">
        <h2>@ViewBag.Title</h2>

        <div class="mb-3 d-flex flex-wrap justify-content-center">
            <a href="@Url.Action("Create")" class="btn btn-info me-3 mb-2">+ Add Product</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="@Url.Action("Index", "Stocks")" class="btn btn-info me-3 mb-2">Stocks</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="@Url.Action("Reports", "Products")" class="btn btn-info mb-2">Products Info</a>
        </div>
        <table class="table table-bordered table-striped align-middle">
            <thead class="table-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>SubCategory</th>
                    <th>Price (₹)</th>
                    <th>Stock Id</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var p in Model)

                {
    <tr>
        <td>@p.ProductId</td>
        <td>@p.ProductName</td>
        <td>@p.CategoryName</td>
        <td>@p.SubCategoryName</td>
        <td>@p.Cost</td>
        <td>@p.Stock_Id</td>
        <td>
            <a href="@Url.Action("Edit", new { id = p.ProductId })" class="btn btn-sm btn-outline-primary">Edit</a>
            <a href="@Url.Action("Delete", new { id = p.ProductId })" class="btn btn-sm btn-outline-danger">Delete</a>
        </td>
    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Team_1_Finance_(Major_Project)/IKart/IKart_Client/Views/Products/Reports.cshtml
@model List<IKart_Shared.DTOs.Admin.StocksDto>

@{
                Layout = "~/Views/Shared/_AdminLayout.cshtml";

                ViewBag.Title = "Products Report";

}

<div class="container mt-4">
    <div class="card shadow-sm border-0 p-4">
        <h2 class="text-center mb-4">@ViewBag.Title</h2>

        <table class="table table-bordered align-middle">
            <thead class="table-dark">
                <tr>
                    <th>Category</th>
                    <th>SubCategory</th>
                    <th>Total Stocks</th>
                    <th>Available Stocks</th>
                </tr>
            </thead>
            <tbody>

                @{
                                string currentCategory = null;

                                int categoryTotal = 0;

                                int categoryAvailable = 0;

                }

                @foreach (var item in Model)

                {

                    if (currentCategory != item.Category && currentCategory != null)

                    {
    <tr class="table-secondary fw-bold">
        <td colspan="2">Total (@currentCategory)</td>
        <td>@categoryTotal</td>
        <td>@categoryAvailable</td>
    </tr> categoryTotal = 0;

                        categoryAvailable = 0;

                    }

                    currentCategory = item.Category;

                    categoryTotal += item.TotalStocks ?? 0;

                    categoryAvailable += item.AvailableStocks ?? 0;

    <tr>
        <td>@item.Category</td>
        <td>@item.SubCategory</td>
        <td>@item.TotalStocks</td>
        <td>@item.AvailableStocks</td>
    </tr>
                }

                @if (currentCategory != null)

                {
    <tr class="table-secondary fw-bold">
        <td colspan="2">Total (@currentCategory)</td>
        <td>@categoryTotal</td>
        <td>@categoryAvailable</td>
    </tr>
                }
            </tbody>
        </table>

        <div class="text-center mt-3">
            <a href="@Url.Action("Index", "Products")" class="btn btn-secondary px-4">⬅ Back</a>
        </div>
    </div>
</div>